defaults:
  - _self_
  - config: unet

hydra:
  run:
    dir: ${config.output_dir}/${hydra:job.name}-${now:%Y-%m-%d}/${now:%H-%M-%S}

# overall settings, will be overwrited by the local settings
config:
  data:
    # TOF
    # source_path: "/disk/cyq/tof_data_nii/train/source_nii"
    # label_path: "/disk/cyq/tof_data_nii/train/label1_nii"
    # test_source_path: "/disk/cyq/tof_data_nii/test/source_nii"
    # test_label_path: "/disk/cyq/tof_data_nii/test/label1_nii"
    # MIDAS
    source_path: "/disk/Brain-MR/train/source"
    label_path: "/disk/Brain-MR/train/label"
    test_source_path: "/disk/Brain-MR/test/source"
    test_label_path: "/disk/Brain-MR/test/label"
    suffix: "nii.gz"
    patch_size: [64, 64, 64]
    batch_size: 4
    num_workers: 0
    num_samples: 4 # sample num_samples in a image
    pos_ratio: 1 # positive ratio
    neg_ratio: 0 # negative ratio
    cache: True
    cache_rate: 1
  pl_models:
    lr: 0.01
    patch_size: [64, 64, 64]
    sw_batch_size: 8
    show_model_stats: True
    init_type: "kaiming"
    save_path: ${hydra:runtime.output_dir}
    use_scheduler: True
    lr_step_size: 20
    lr_gamma: 0.8
  trainer:
    benchmark: True
    devices: [1]
    accelerator: "auto"
    max_epochs: 100

  job_name: ${hydra:job.name}
  hydra_path: ${hydra:runtime.output_dir}

